## Mode

In [ ]:
Most frequent / reapeated value / most occured
> mostly used for categorical data
> it return repeated number / value and its count

In [4]:
from scipy.stats import mode
import numpy as np

In [10]:
array1 = np.array([17,26,26,25,26])
Mode = mode(array1)
print("Mode\n",Mode)
value = Mode[0][0]
print("Value>>\n",value)

Mode
 ModeResult(mode=array([26]), count=array([3]))
Value>>
 26


In [ ]:
# Smoker
yes
no

No
Yes   # knn > k=5 Yes (3) vs NO(2) >> 
 
No
# Static value
# Mode
# 

## Trignomentry

## 1) np.sin()

In [ ]:
sin = opp/Hyp
cos = Adj/Hyp
tan = opp/Adj

cot = Adj/Opp = 1/tan

In [11]:
import math

In [12]:
math.pi
np.pi >>> # it return pi value in radian

3.141592653589793

In [14]:
np.sin(np.pi/6)   # 180/6 = 30  >> radian

0.49999999999999994

In [15]:
np.sin(np.pi/3)   # 180/3 = 60  >> radian

0.8660254037844386

In [16]:
np.sin(np.pi/2)   # 180/2 = 90  >> radian

1.0

In [17]:
np.sin(0)   # 180/2 = 90  >> radian

0.0

## 2.cos

In [18]:
np.cos(np.pi/6) # cos(30)

0.8660254037844387

In [19]:
np.cos(np.pi/4) # cos(45)

0.7071067811865476

## 3.tan

In [20]:
np.tan(np.pi/6)

0.5773502691896257

In [21]:
np.tan(np.pi/4)

0.9999999999999999

## degree to radians

In [22]:
np.deg2rad(45)

0.7853981633974483

In [23]:
np.deg2rad(30)

0.5235987755982988

In [24]:
np.sin(np.pi/6) # sin(30) = 180/6 = 30

0.49999999999999994

In [26]:
np.sin(np.deg2rad(30)) # sin(30) = 180/6 = 30

0.49999999999999994

In [25]:
np.pi/6 # converting to radian

0.5235987755982988

In [27]:
rad_values = np.deg2rad([0,30,45,60,90])
np.sin(rad_values)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [28]:
rad_values = np.deg2rad([0,30,45,60,90])
np.cos(rad_values)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

## Radian to degree

In [31]:
de # converting to degree to rad
print("RADIAN VALUES\n",rad_values)
print("*"*20)
deg_values = np.rad2deg(rad_values) # rad to degree
print("Degree values \n",deg_values)

RADIAN VALUES
 [0.         0.52359878 0.78539816 1.04719755 1.57079633]
********************
Degree values 
 [ 0. 30. 45. 60. 90.]


In [ ]:
deg2rad()

## log

In [ ]:
Basically It is use to reduce the imapact of outliers in data
1) np.log (Natural log)
2) np.log10
3) np.log2


## 1) np.log

In [ ]:
Natural Log

In [32]:
np.log(50)

3.912023005428146

In [33]:
arra = np.random.randint(10,20,size=(2,2))
print("Array\n",arra)
np.log(arra)

Array
 [[16 14]
 [15 10]]


array([[2.77258872, 2.63905733],
       [2.7080502 , 2.30258509]])

## CASE 1

In [38]:
arra = np.array([2,3,4,5,6,7])
print("Array\n",arra)
np.mean(arra)  # Without outliers

Array
 [2 3 4 5 6 7]


4.5

In [42]:
arra = np.array([2,3,4,5,6,700])
print("Array\n",arra)
np.mean(arra)  # # With outliers

Array
 [  2   3   4   5   6 700]


120.0

In [ ]:
# Log concept

In [40]:
arra = np.array([2,3,4,5,6,7])
print("Array\n",arra)
arra2 = np.log(arra)
print("Array2\n",arra2)
np.mean(arra2)

Array
 [2 3 4 5 6 7]
Array2
 [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947 1.94591015]


1.4208602268442359

In [43]:
arra = np.array([2,3,4,5,6,700])
print("Array\n",arra)
arra2 = np.log(arra)
print("Array2\n",arra2)
np.mean(arra2)

Array
 [  2   3   4   5   6 700]
Array2
 [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947 6.55108034]


2.1883885911755843

In [47]:
arra = np.array([2,3,4,5,6,700])
print("Array\n",arra)
arra2 = np.log10(arra)
print("Array2\n",arra2)
np.mean(arra2)

Array
 [  2   3   4   5   6 700]
Array2
 [0.30103    0.47712125 0.60205999 0.69897    0.77815125 2.84509804]


0.9504050894075875

## 2) np.log2

In [44]:
np.log2(40)

5.321928094887363

In [45]:
np.log(40)

3.6888794541139363

In [46]:
np.log10(40)

1.6020599913279623

In [48]:
lst = [3,4,5,6,7,8,3,6,3,9]  # index of 3 [0,6,8] 
array = np.array(lst)
print("Array\n",array)
print()
np.where(array == 3) # condition array == 3

Array
 [3 4 5 6 7 8 3 6 3 9]



(array([0, 6, 8], dtype=int64),)

In [50]:
lst = [3,4,5,6,7,8,3,6,3,9]  # index of 3 [0,6,8] 
array = np.array(lst)
print("Array\n",array)
print()
result = array[np.where(array == 3)] # condition array == 3
result

Array
 [3 4 5 6 7 8 3 6 3 9]



array([3, 3, 3])

In [51]:
lst = [3,4,5,6,7,8,3,6,3,9]  # index of  [7,8,9] 
array = np.array(lst)
print("Array\n",array)
print()
result = array[np.where(array >= 7)] # condition array == 3
result

Array
 [3 4 5 6 7 8 3 6 3 9]



array([7, 8, 9])

In [52]:
lst = [3,4,5,6,7,8,3,6,3,9]  # index of  [7,8,9] 
array = np.array(lst)
print("Array\n",array)
print()
result = array[np.where(array > 6)] # condition array == 3
result

Array
 [3 4 5 6 7 8 3 6 3 9]



array([7, 8, 9])

## sqrt

In [54]:
lst = [25,64,100,4]
array = np.array(lst)
print("Array\n",array)
print()
np.sqrt(array)

Array
 [ 25  64 100   4]



array([ 5.,  8., 10.,  2.])

In [55]:
lst = [25,64,100,4]
array = np.array(lst)
print("Array\n",array)
print()
array ** 0.5

Array
 [ 25  64 100   4]



array([ 5.,  8., 10.,  2.])

In [57]:
lst = [25,64,100,4]
[i**0.5 for i in lst]

[5.0, 8.0, 10.0, 2.0]

In [59]:
lst = [25,64,100,4]
list(map(lambda x :x**0.5,lst))

[5.0, 8.0, 10.0, 2.0]

In [60]:
lst = [25,64,100,4]
lst1 = []
for i in lst:
    lst1.append(i**0.5)
lst1

[5.0, 8.0, 10.0, 2.0]

In [61]:
# [5,5,5,5,5,5,5,5,5,5]
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

## Transpose

In [62]:
arra = np.random.randint(10,20,size=(2,2))
print("Array\n",arra)  
# o/p
[[18 10]
 [11 15]]

Array
 [[18 11]
 [10 15]]


In [63]:
arra.T

array([[18, 10],
       [11, 15]])

## QUES

In [65]:
lst = [3,4,5,6,70,8,3,6,3,9]  # index of  [7,8,9] 
array = np.array(lst)
print("Array\n",array)
print()
np.where(array == np.max(array))

Array
 [ 3  4  5  6 70  8  3  6  3  9]



(array([4], dtype=int64),)

In [66]:
lst = [3,4,5,6,70,8,3,6,3,9]  # index of  [7,8,9] 
array = np.array(lst)
print("Array\n",array)
print()
np.where(array == array.max())

Array
 [ 3  4  5  6 70  8  3  6  3  9]



(array([4], dtype=int64),)

In [68]:
lst = [3,400,5,6,70,8,3,6,3,9]  # index of  [7,8,9] 
array = np.array(lst)
print("Array\n",array)
print()
array.argmax()

Array
 [  3 400   5   6  70   8   3   6   3   9]



1

In [69]:
lst = [3,400,5,6,70,8,3,6,3,9]  # index of  [7,8,9] 
array = np.array(lst)
print("Array\n",array)
print()
array.argmin()

Array
 [  3 400   5   6  70   8   3   6   3   9]



0

## ques

In [70]:
lst = [1,2,3,4]  # [1,2,3,4,1,2,3,4]
arr1 = np.array(lst)
arr2 = np.array(lst)
np.concatenate([arr1,arr2])

array([1, 2, 3, 4, 1, 2, 3, 4])

In [71]:
lst * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [72]:
np.tile(lst,2)

array([1, 2, 3, 4, 1, 2, 3, 4])

## ques

In [ ]:
lst = [1,2,3,4]  # [1,1,2,2,3,3,4,4]

In [74]:
np.sort(np.tile(lst,2))

array([1, 1, 2, 2, 3, 3, 4, 4])

In [75]:
np.repeat(lst,2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [77]:
lst = [1,2,3,4]  
arr1 = np.array(lst)
arr2 = np.array(lst)
np.sort(np.append(arr1,arr2))

array([1, 1, 2, 2, 3, 3, 4, 4])