In [ ]:
data1_age = 12,20,30,40,400,50 = mean()
data2_age = 12,20,30,40,40,50  = mean()

### Numpy

In [ ]:
Numpy > Numerical Python

## Applications

In [ ]:
1) Linear regression
2) Statistics  (mean,mode,median,std,variance)
3) Probability
4) Trignomentry (tan,cos,sin,cosine etc)
5) calculs
6) Meatrix
7) Linear alegrbra   5x + 2y =3 and 5x+ 3y=1 
8) Random Number Generation

In [3]:
import numpy as np

In [4]:
lst = ["1",2,3.4]
lst

['1', 2, 3.4]

In [5]:
lst = ["1",2,3.4]
n1  = np.array(lst)
n1

array(['1', '2', '3.4'], dtype='<U32')

In [10]:
n2 = np.array([5,3.3,4,2+3j,"4"]) # 
print(n2)

['5' '3.3' '4' '(2+3j)' '4']


In [11]:
n2 = np.array([5,3.3,4,2+3j]) # 
print(n2)

[5. +0.j 3.3+0.j 4. +0.j 2. +3.j]


In [12]:
n2 = np.array([5,3.3,4,2]) # 
print(n2)

[5.  3.3 4.  2. ]


In [13]:
n2 = np.array([5,3,4,6]) # 
print(n2)

[5 3 4 6]


## Properties of Numpy

In [ ]:
1) It is collection of Homogenous data type
2) Numpy is faster than list(Hetrogeneous) 
3) Numpy is written in C/C++ langauge and partially written in python
4) ndarray >> n dimensional array (0D,1D,2D,3D....nD)
5) Array can be creatd using python dta type i.e list/tuple

In [17]:
# List
lst = [1,2,3,"4",5.5]
arr1 = np.array(lst)
arr1

array(['1', '2', '3', '4', '5.5'], dtype='<U32')

In [18]:
# tuple
lst = (1,2,3,"4",5.5)
arr1 = np.array(lst)
arr1

array(['1', '2', '3', '4', '5.5'], dtype='<U32')

In [19]:
# tuple
dict1 = {"tuple1":(1,2,3,"4",5.5)}
arr1 = np.array(dict1)
arr1 # wrong way

array({'tuple1': (1, 2, 3, '4', 5.5)}, dtype=object)

## change datatype

In [ ]:
# convert to int

In [16]:
n2 = np.array([5,3.3,4,2],dtype=int) # 
n2

array([5, 3, 4, 2])

In [ ]:
# convert to complex

In [20]:
n2 = np.array([5,3.3,4,2],dtype=complex) # 
n2

array([5. +0.j, 3.3+0.j, 4. +0.j, 2. +0.j])

In [21]:
n2 = np.array([5,3.3,4,2],dtype=float) # 
n2

array([5. , 3.3, 4. , 2. ])

In [22]:
n2 = np.array([5,3.3,4,2],dtype=str) # 
n2

array(['5', '3.3', '4', '2'], dtype='<U3')

In [23]:
n2 = np.array([5,3.3,4,2+3j],dtype=int) # 
n2

TypeError: can't convert complex to int

In [26]:
n2 = np.array([5,3.3,4,"2"],dtype=int) # 
n2

array([5, 3, 4, 2])

In [27]:
a = (input("Enter the value::::"))
type(a)

Enter the value::::4


str

In [25]:
a = int(input("Enter the value::::"))
type(a)

Enter the value::::4


int

In [ ]:
# conclusion
int >float,complex,str
float > int,complex,str
complex> not int,not float

## Numpy Functions

1) np.array()
2) array.tolist() >> N-dimensional numpy array convert to list
3) array.ndim  # to know dimension of array
4) array.shape > to know the shape of array

## 1) np.array()

In [28]:
lst = [2,3,4,5,5.5]
arr1 = np.array(lst)
arr1

array([2. , 3. , 4. , 5. , 5.5])

## 2) arr1.tolist()

In [30]:
# question >> 
# i/p[2,3,4,5,6] >> o/p[4,9,16,25,36]
lst = [2,3,4,5,6] 
o_p = list(map(lambda x:x**2,lst))
o_p

[4, 9, 16, 25, 36]

In [40]:
lst = [2,3,4,5,6] 
o_p = []
for i in lst:
    o_p.append(i**2)
o_p

[4, 9, 16, 25, 36]

In [35]:
lst = [2,3,4,5,6] 
o_p = [i**2 for i in lst]
o_p

[4, 9, 16, 25, 36]

In [42]:
lst = [2,3,4,5,6]
arr1 = np.array(lst)**2
arr1  # array o/p

array([ 4,  9, 16, 25, 36], dtype=int32)

In [39]:
lst = [2,3,4,5,6]
arr1 = np.array(lst)**2
arr1.tolist() # list as o/p

[4, 9, 16, 25, 36]

In [41]:
lst = [2,3,4,5,6]
lst = (np.array(lst)**3).tolist()
lst # list as o/p

[8, 27, 64, 125, 216]

## 3) array.ndim

## 3.1 0-D

In [ ]:
only single value

In [43]:
arr0 = np.array(12)
print("Number of dimension are \n:",arr0.ndim)

Number of dimension are 
: 0


## 3.2 1-D

In [ ]:
it is collection of multiple 0-D array >> it means list etc

In [45]:
arr1 = np.array([12,13,14,15])
print("Number of dimension are \n:",arr1.ndim)

Number of dimension are 
: 1


## 3.2 2-D

In [ ]:
It is collection of multiple 1-D array >> it means matrix

In [46]:
arr1 = np.array([[12,13,14,15],[12,13,14,15],[12,13,14,15],[12,13,14,15]])
print("Number of dimension are \n:",arr1.ndim)

Number of dimension are 
: 2


## 3.3 3-D

In [ ]:
It is collection of multiple 2-D array 

In [47]:
arr1 = np.array([[[12,13,14,15],[12,13,14,15]]])
print("Number of dimension are \n:",arr1.ndim)

Number of dimension are 
: 3


## 4) array.shape

In [49]:
arr1 = np.array([[[12,13,14,15],[12,13,14,15]]])
print("Number of dimension are \n:",arr1.ndim)
print(arr1)
print("Shape of array\n:",arr1.shape)

Number of dimension are 
: 3
[[[12 13 14 15]
  [12 13 14 15]]]
Shape of array
: (1, 2, 4)


In [51]:
arr1 = np.array([[12,13,14,15],[12,13,14,15],[12,13,14,15],[12,13,14,15]])
print("Number of dimension are \n:",arr1.ndim) # 2D
print(arr1)
print("Shape of array\n:",arr1.shape)

Number of dimension are 
: 2
[[12 13 14 15]
 [12 13 14 15]
 [12 13 14 15]
 [12 13 14 15]]
Shape of array
: (4, 4)


In [53]:
arr1 = np.array([12,13,14,15])
print("Number of dimension are \n:",arr1.ndim)
print(arr1)
print("Shape of array\n:",arr1.shape)

Number of dimension are 
: 1
[12 13 14 15]
Shape of array
: (4,)


In [54]:
arr1 = np.array([12,13,14,15,67,4])
print("Number of dimension are \n:",arr1.ndim)
print(arr1)
print("Shape of array\n:",arr1.shape)

Number of dimension are 
: 1
[12 13 14 15 67  4]
Shape of array
: (6,)


In [55]:
arr1 = np.array([[12,13,14,15,67,4]])
print("Number of dimension are \n:",arr1.ndim)
print(arr1)
print("Shape of array\n:",arr1.shape) # (1,6) >>row :column

Number of dimension are 
: 2
[[12 13 14 15 67  4]]
Shape of array
: (1, 6)
